spring.application.name=job-tracker

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

claude.api.key=${CLAUDE_API_KEY:}

frontend.url=${FRONTEND_URL:http://localhost:5173}

logging.level.com.treydev.job_tracker.service.ResumeAnalysisService=DEBUG
